### ISSUE TITLE
If no firstname or username, show nothing on requests instead of user email

### ISSUE THREAD

**Issue by markmacgillivray** [OAButton/discussion#622]

**Comment by JosephMcArthur** [comment]
use "anonymous", or a form of it.

**Comment by markmacgillivray** [comment]
Done, and user firstnames loaded into old requests where possible. However, most of the new ones that can be seen by admins did not end up with user details added into them, because they are mostly requests created where nobody has taken ownership of them. So they show up as "an anonymous user"

**Comment by JosephMcArthur** [comment]
99% of these seems much better. Still seeing one though: https://openaccessbutton.org/request?source={%22query%22:{%22filtered%22:{%22query%22:{%22bool%22:{%22must%22:[{%22query_string%22:{%22default_operator%22:%22AND%22,%22query%22:%22i%20need%20this%20dataset%20to%20make%20my%20project%20in%20classification%20of%20dolphin%20or%20whale%20types%20by%20sounds%20that%20they%20make%22}}]}},%22filter%22:{%22bool%22:{%22must%22:[{%22exists%22:{%22field%22:%22story%22}},{%22query%22:{%22query_string%22:{%22query%22:%22story:*%22}}}]}}}},%22from%22:0,%22size%22:500,%22fields%22:[%22status%22,%22type%22,%22user.profession%22,%22user.affiliation%22,%22_id%22,%22url%22,%22created_date%22,%22createdAt%22,%22title%22,%22email%22,%22user.username%22,%22user.firstname%22,%22user.email%22,%22location.geo.lat%22,%22location.geo.lon%22,%22story%22,%22count%22],%22sort%22:[{%22createdAt%22:%22desc%22}],%22facets%22:{%22status%22:{%22terms%22:{%22field%22:%22status.exact%22}},%22user%22:{%22terms%22:{%22field%22:%22user.profession.exact%22}},%22type%22:{%22terms%22:{%22field%22:%22type.exact%22}},%22keyword%22:{%22terms%22:{%22field%22:%22keywords.exact%22,%22size%22:1000}},%22journal%22:{%22terms%22:{%22field%22:%22journal.exact%22,%22size%22:1000}}}}

which is fixed when you look at the reqeust page itself. Did we apply the fix to /requests?

**Comment by markmacgillivray** [comment]
Yeah I did add the it to the /request search page too, and filtered out where usernames were email addresses, but that record had an odd format error in the field so it was not filtering it properly. I have fixed it and it is getting pushed to live now.
