### ISSUE TITLE
oasheet sending wrong email

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#929]

**Comment by markmacgillivray** [comment]
Fixed on my system and pushing to dev, however as jobs are not currently running this cannot be tested. However I have tested locally and it works now, sending the correct email with the link to download the results. So once jobs are turned back on, this will work.

**Comment by JosephMcArthur** [comment]
Seems like it's still not quite sending what is in the dev email template. 

The email I get doesn't have exactly the same text as is in /emails/bulk_complete.html. What I get is:

> Hi, joseph.mcarthur.10@gmail.com!
> 
> Your bulk job OASheet examples - example input.csv is complete. You can download your results here.
> 
> Best,
> 
> Joe

On dev, the download link for the results also doesn't work. Maybe related to #939. 

I get sent to https://api.openaccessbutton.org/job/ZZ5F3izZJMABMyn5S/results.csv which just gives:

> Server error.

**Comment by markmacgillivray** [comment]
The link will be wrong because the template includes the URL of the live API. The code did have some way to replace that with the dev API so that testing emails would work, but at the moment we are on a different dev API (the new code) so the links you get will be wrong. You can test they work by manually replacing https://api.openaccessbutton.org with https://noddy.api.cottagelabs.com/service/oab in your URL bar.

As to the text not being what you expect, looks like the email templates just needed refreshed. Try again.

**Comment by JosephMcArthur** [comment]
ah yes, the links work now and the email text is up to date (sorry for not testing the obvious there!). 

Will the links start automatically correcting themselves for dev at some point, or is it worth keeping this issue open to fix that?

**Comment by markmacgillivray** [comment]
Yes
